name: internship-aggregator

services:
  # ---- Kafka 4.2.0 (KRaft mode)
  kafka:
    image: apache/kafka:4.2.0
    container_name: internship-kafka
    ports:
      - "9094:9094" #на локалхост 9094 проброс, хотя это не надо, у нас она живёт в докере, потом спрячем
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@internship-kafka:9093
      
      # Слушатели: 
      # 9092 - внутри Docker сети (для Kafka UI)
      # 9094 - снаружи для хоста (через localhost)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://internship-kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # Данные и репликация
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"

      #время нормальное
      TZ: "Europe/Moscow"

    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-c", 'printf "" > /dev/tcp/127.0.0.1/9092']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # юай нормик
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: internship-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: internship-kafka:9092
      
      # короче подсос прото пока не работает потом починим это фигня
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT

      TZ: "Europe/Moscow"
    volumes:
      - ./proto:/etc/kafka-ui/proto:ro  
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network

  # ---- PostgreSQL 18.2
  postgres:
    image: postgres:18.2-alpine
    container_name: internship-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: aggregator
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Europe/Moscow"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d aggregator" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


    # ---- Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: internship-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_CONTEXT_LENGTH=16384
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  # ---- Caddy 
  caddy:
    image: caddy:2.9-alpine
    container_name: internship-caddy
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - kafka-ui
      - frontend
    networks:
      - app-network

  parser:
    build: ./scrapper
    container_name: internship-parser
    environment:
      - TZ=Europe/Moscow
    depends_on:
      kafka:
        condition: service_healthy
      ollama:
        condition: service_healthy
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

 # ---- Manual Control (Admin Panel)
  manual-control:
    build:
      context: ./manual-control
      dockerfile: Dockerfile
    container_name: internship-manual-control
    ports:
      - "2228:2228"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - PORT=2228
      - TZ=Europe/Moscow
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2228/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  frontend:
    build: ./internhub
    container_name: internship-frontend
    restart: unless-stopped
    networks:
      - app-network
      
volumes:
  kafka_data:
  ollama_data:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    name: internship-network